### ISSUE TITLE
Cannot extend editor.ui.view template

### ISSUE THREAD

**Issue by alexeckermann** [alexeckermann/ckeditor5-emptyness#5]
`editor.ui.view` is not directly extendable as an editor may not define its template in that view alone. An `EditorUIView` subclass may be a container which references several distinct child views which may or may not be structurally contained within this view in the DOM, or if the view has a DOM element at all. This was a misunderstanding based upon an incorrect test environment.

The `ClassicTestEditor` initialises the editor differently to a non-test `ClassicEditor`, rendering before its supposed to. Moreover, the structure of this test editor lead to a misunderstand of what a typical editor structure is and what view is available to have its template extended. This issue is being resolved in [ckeditor5-core#137](https://github.com/ckeditor/ckeditor5-core/issues/137).

However, the plugin must be more resilient to handle the very rare case where a new or updated editor class does not have a known view to extend.

**Comment by alexeckermann** [comment]
Pull request #6 [failed to rectify the problem](https://github.com/alexeckermann/ckeditor5-emptyness/pull/6#issuecomment-403381067). More work will be needed to find an appropriate state method for extending the editable view.

**Comment by alexeckermann** [comment]
PR's related to ckeditor/ckeditor5#1150 will resolve this issue.

Some editor's would call methods that render their `editable` views in their constructors. This prevents any plugin from being able to call `extendTemplate` on any of those rendered views.

**Comment by oleq** [comment]
I merged all PRs related to https://github.com/ckeditor/ckeditor5/issues/1150. Again, huge thanks for your contribution! 👏 

I hope you can take your plugin to the next level now! 🚀🚀🚀

**Comment by alexeckermann** [comment]
Note: To anyone running CK v11.0 and experiencing issues with variables in editors other than `ClassicEditor` please use the branch `issue-5`. Some editors will also require the upstream release of iteration 20 by the CK team before this issue is fully resolved. ETA very soon.

**Comment by alexeckermann** [comment]
With the release of CKEditor v11.1 comes the changes needed in the editors to fix this issue.

Please see the updated README for updated information on the implementation of this plugin.
